-- *Main> lastButOne [1,2,3]
-- 2
-- *Main> lastButOne [1,2,3,3,3,3,5,7,6,8]
-- 6
-- *Main> lastButOne [1]
-- *** Exception: Prelude.last: empty list
-- *Main> lastButOne []
-- *** Exception: Prelude.init: empty list
